/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FacilitiesIndexRouteImport } from './routes/facilities.index'
import { Route as FacilitiesFacilityIdRouteImport } from './routes/facilities.$facilityId'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FacilitiesIndexRoute = FacilitiesIndexRouteImport.update({
  id: '/facilities/',
  path: '/facilities/',
  getParentRoute: () => rootRouteImport,
} as any)
const FacilitiesFacilityIdRoute = FacilitiesFacilityIdRouteImport.update({
  id: '/facilities/$facilityId',
  path: '/facilities/$facilityId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/facilities/$facilityId': typeof FacilitiesFacilityIdRoute
  '/facilities/': typeof FacilitiesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/facilities/$facilityId': typeof FacilitiesFacilityIdRoute
  '/facilities': typeof FacilitiesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/facilities/$facilityId': typeof FacilitiesFacilityIdRoute
  '/facilities/': typeof FacilitiesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/facilities/$facilityId'
    | '/facilities/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/register' | '/facilities/$facilityId' | '/facilities'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/register'
    | '/facilities/$facilityId'
    | '/facilities/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  FacilitiesFacilityIdRoute: typeof FacilitiesFacilityIdRoute
  FacilitiesIndexRoute: typeof FacilitiesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/facilities/': {
      id: '/facilities/'
      path: '/facilities'
      fullPath: '/facilities/'
      preLoaderRoute: typeof FacilitiesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/facilities/$facilityId': {
      id: '/facilities/$facilityId'
      path: '/facilities/$facilityId'
      fullPath: '/facilities/$facilityId'
      preLoaderRoute: typeof FacilitiesFacilityIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  FacilitiesFacilityIdRoute: FacilitiesFacilityIdRoute,
  FacilitiesIndexRoute: FacilitiesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
